# -*- coding: utf-8 -*-
"""covid 19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X-89WdH6H1YqbCREQdXJZBhViNRQN9RL
"""

import numpy as np
import pandas as pd
from fbprophet import Prophet

covid= pd.read_csv("covid_19_clean_complete.csv", parse_dates = ['Date'])

covid.head()

covid['Active'] = covid['Confirmed'] - covid['Deaths'] + covid['Recovered']
covid.head()

confirmed= covid.groupby('Date')['Confirmed'].sum().reset_index()

confirmed = confirmed.rename(columns= {'Date':'ds', 'Confirmed': 'y'})
confirmed.head()

model= Prophet()
model.fit(confirmed)

future = model.make_future_dataframe(periods=7)

forecast= model.predict(future)

forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(7)

conf_plot= model.plot(forecast)

active= covid.groupby('Date')['Active'].sum().reset_index()

active = active.rename(columns= {'Date':'ds', 'Active': 'y'})
active.head()

model= Prophet()
model.fit(active)

future = model.make_future_dataframe(periods=7)

forecast= model.predict(future)

forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(7)

Active_plot= model.plot(forecast)

deaths= covid.groupby('Date')['Deaths'].sum().reset_index()

deaths = deaths.rename(columns= {'Date':'ds', 'Deaths': 'y'})
deaths.head()

model= Prophet()
model.fit(deaths)

future = model.make_future_dataframe(periods=7)

forecast= model.predict(future)

forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(7)

deaths_plot= model.plot(forecast)