# -*- coding: utf-8 -*-
"""Eye clinic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C8Ikx_nRx9At4CjW46TPVE_yRkQbLfsz

IMPORTING LIBRRARIES
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""LOADING THE DATA"""

eye_clinic= pd.read_excel('/content/drive/My Drive/EyeClinic_Sample.xlsx', parse_dates= True)

"""CHECKING THE FIRST FIVE ROWS OF DATA"""

eye_clinic.head(5)

"""CHECKING THE THE DATA TYPES IN THE DATA"""

eye_clinic.info()

"""CHECKING FOR MISSING VALUES IN THE DATA"""

sns.heatmap(eye_clinic.isnull(), cmap= 'Blues', cbar= False, yticklabels= False)

"""There are some missing values in the billdate column."""

eye_clinic[eye_clinic['billdate'].isnull()]

"""DROPPING THE MISSING VALUES"""

eye_clinic= eye_clinic.dropna()

sns.heatmap(eye_clinic.isnull(), cmap= 'Blues', cbar= False, yticklabels= False)

"""FINDING THE MOST SELLING LENSES IN RTSPH COLUMN."""

lenses= [-0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.25, -2.50, -3.0, -3.5, -4.0, -4.5, -5.0, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0]

counter=0
right_lens=[]
for i in lenses:
  for j in eye_clinic['RtSph']:
    if j == i:
      counter= counter + 1
  print("Number of {} sph lens sold is {}:".format(i, counter))
  right_lens.append(counter)

right_lens

len(right_lens)

"""FINDING THE MOST SELLING LENSES IN LTSPH COLUMN."""

lenses= [-0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.25, -2.50, -3.0, -3.5, -4.0, -4.5, -5.0, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0]

counter= 0
left_lens=[]
for i in lenses:
  for j in eye_clinic['LtSph']:
    if j == i:
      counter= counter + 1
  print("Number of {} sph lens sold is {}:".format(i, counter))
  left_lens.append(counter)

left_lens

len(left_lens)

"""FINDING THE TOTAL NUMBER OF LENSES SOLD OF EACH TYPE"""

total_lens = [] 

for i in range(0, len(right_lens)): 
    total_lens.append(right_lens[i] + left_lens[i]) 
    print("Total number of {} sph lens sold is {}".format(lenses[i], total_lens[i]))

"""We can clearly see that the total number of +2.0 sph lenses sold is the maximum and the total number of -0.5 sph lenses sold is the minimum."""

total_lens

len(total_lens)

total_lens.sort(reverse= True)
total_lens

"""Since we have the total number of lenses sold for each type of lens. We can now put them in buckets in order of their importance. So the most important lenses will go in bucket B1, the 2nd important ones will go to bucket B2 and so on.

So the buckets will contain lenses in the following order:

1) B1 - +2.0, +1.5, +1.25, +1.0, +0.75

2) B2 - +0.5, -5.0, -4.5, -4.0, -3.5

3) B3 - -3.0, -2.5, -2.25, -2.0, -1.75

4) B4- -1.5, -1.25, -1.0, -0.75, -0.5
"""

