# -*- coding: utf-8 -*-
"""Indian Premier League(EDA).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ovdAesAD8JsYU-nFbffXYCiU0BS8l93q

# **VIKASH NAG**

# Exploratory Data Analysis - Sports (Level - Advanced)

● Perform ‘Exploratory Data Analysis’ on dataset  ‘Indian Premier League’

● As a sports analysts, find out the most successful teams, players and factors contributing win or loss of a team. 

● Suggest teams or players a company should endorse for its products.

● You can choose any of the tool of your choice  (Python/R/Tableau/PowerBI/Excel/SAP/SAS) 

● Dataset:https://bit.ly/34SRn3b

● Advanced Level - Create storyboards. Screen-record along with your audio explaining the charts and interpretations. Use annotations, animation and images.

● Task submission: 
1. Create the dashboards and/or storyboard and record it 

2. Upload the recording on Youtube, share the link on LinkedIn 

3. Submit LinkedIn post link in Task Submission Form when shared

### IMPORTING NECESSARY LIBRARIES
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""# EXPLORATORY DATA ANALYSIS OF DELIVERIES.CSV DATA

IMPORTING THE DATASET
"""

deliveries= pd.read_csv('/content/drive/My Drive/Datasets/IPL/deliveries.csv')

deliveries.head()

deliveries .tail()

deliveries.info()

"""CHECKING FOR MISSING VALUES"""

sns.heatmap(deliveries.isnull(), yticklabels= False, cbar= False, cmap= 'Blues')

"""We can see that there are null values in 'player_dismissed', 'dismissal_kind' and 'fielder' columns."""

deliveries.isnull().sum()

"""Since there are so many missing values in the last three columns, we need to drop these columns."""

deliveries.drop([ 'player_dismissed', 'dismissal_kind', 'fielder'], axis= 1, inplace= True)

deliveries.isnull().sum()

"""FINDING UNIQUE VALUES OF EACH COLUMNS"""

for i in deliveries.columns:
  print("Unique values in {} column is{}:".format(i, np.unique(deliveries[i])))
  print("---------------------------------------------------------------------------------------------------------")

"""As we can see that 'Rising Pune Supergiant' and 'Rising Pune Supergiants' are repeated in batting team and bowling team columns. So we need to make it one."""

deliveries['batting_team'].replace('Rising Pune Supergiants', 'Rising Pune Supergiant', inplace= True)

deliveries['bowling_team'].replace('Rising Pune Supergiants', 'Rising Pune Supergiant', inplace= True)

np.unique(deliveries['batting_team'])

np.unique(deliveries['bowling_team'])

"""# EXPLORATORY DATA ANALYSIS OF MATCHES.CSV DATA

IMPORTING THE DATASET
"""

matches= pd.read_csv('/content/drive/My Drive/Datasets/IPL/matches.csv', parse_dates= True)

matches.head()

matches.tail()

matches.info()

np.unique(matches['season'])

"""matches.csv data contains data of IPL matches from 2008 - 2019.

FINDING MISSING VALUES
"""

sns.heatmap(matches.isnull(), yticklabels= False, cbar= False, cmap= 'Blues')

"""Since there are so many missing values in the last coumn, we need to drop it and fill the values in the rest of the columns."""

matches.isnull().sum()

"""Since 'umpire3' contains so many missing values therefore we need to drop it."""

matches.drop('umpire3', axis= 1, inplace= True)

"""FILLING THE MISSING VALUES IN REST OF THE COLUMNS"""

matches['city'].fillna(matches['city'].mode()[0], inplace= True)

matches['winner'].fillna(matches['winner'].mode()[0], inplace= True)

matches['player_of_match'].fillna(matches['player_of_match'].mode()[0], inplace= True)

matches.isnull().sum()

"""We can drop 'umpire1' and umpire2 column as they are of no use."""

matches.drop(['umpire1', 'umpire2'], axis= 1, inplace= True)

"""FINDING UNIQUE VALUES IN COLUMNS"""

np.unique(matches['team1'])

np.unique(matches['team2'])

np.unique(matches['winner'])

"""'Rising Pune Supergiant' is repeated twice with a different name. So we need to make it one."""

matches['team1'].replace('Rising Pune Supergiants', 'Rising Pune Supergiant', inplace= True)

matches['team2'].replace('Rising Pune Supergiants', 'Rising Pune Supergiant', inplace= True)

matches['winner'].replace('Rising Pune Supergiants', 'Rising Pune Supergiant', inplace= True)

"""## Finding the team who has won the most and least matches in IPL."""

plt.figure(figsize= (30, 10))

c= sns.countplot( matches['winner'])
c.axes.set_title("Total number of wins by each team from 2008 to 2019", fontsize= 50)

"""Teams who have the highest wins in IPL from 2008 to 2019.

1) Mumbai Indians.
2) Chennai Super Kings.
3) Kolkata Knight Riders.


Teams who have the least wins in IPL from 2008 to 2019.

1) Kochi Tuskers Kerala.
2) Delhi Capitals.
3) Pune Warriors.

## Finding the players who have been awarded the highest player of match in a particular season
"""

highest_pom= matches.groupby('season')['player_of_match'].max()
highest_pom

"""## Finding the players who have been awarded the least player of match in a particular season"""

lowest_pom= matches.groupby('season')['player_of_match'].min()
lowest_pom

"""## Finding the players who have been awarded the most and least 'player of match' in IPL from 2008 to 2019."""

matches['player_of_match'].value_counts()

"""Players who have received the most 'player of match' in IPL from 2008 to 2019:-

1) CH Gayle
2) AB de Villiers
3) RG Sharma

Players who have received the least 'player of match' in IPL from 2008 to 2019:-

1) DJG Sammy
2) AD Mascarenhas
3) YS Chahal
"""

