# -*- coding: utf-8 -*-
"""Retail(EDA).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MeE_g2lNIe93GzVXoYf7JSqWT-5TZw5K

# **VIKASH NAG**

Exploratory Data Analysis - Retail 

● Perform ‘Exploratory Data Analysis’ on dataset  ‘SampleSuperstore’ 

● As a business manager, try to find out the weak areas where you can work to make more profit.  

● What all business problems you can derive by exploring the  data? 

● You can choose any of the tool of your choice  (Python/R/Tableau/PowerBI/Excel/SAP/SAS) 

● Dataset: https://bit.ly/3i4rbWl

● Beginner Level - Create dashboards. Screen-record along with your audio explaining the charts and interpretations.

● Task submission: 1. Create the dashboards and/or storyboard and record it 2. Upload the recording on Youtube, share the link on LinkedIn 3. Submit LinkedIn post link in Task Submission Form when shared

IMPORTING NECESSARY LIBRARIES
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""LOADING THE DATASET"""

superstore= pd.read_csv('/content/drive/My Drive/Datasets/SampleSuperstore.csv')

"""VIEWING FIRST FIVE ROWS OF THE DATA"""

superstore.head()

superstore.tail()

superstore.info()

"""CHECKING FOR MISSING VALUES"""

sns.heatmap(superstore.isnull(), yticklabels= False, cbar= False, cmap= 'Blues')

"""There are no missing values in the dataset.

CHECKING FOR UNIQUE VALUES
"""

for i in superstore.columns:
  print("Unique values in {} column is {}".format(i, np.unique(superstore[i])))
  print("------------------------------------------------------------------------------------------------------------------------------------------")

"""STATISTICAL ANALYSIS OF THE DATA"""

superstore.describe()

"""UNIVARIATE ANALYSIS OF THE DATA"""

plt.figure(figsize= (12, 6))

sns.distplot(superstore['Sales'])

plt.figure(figsize= (12, 6))

sns.kdeplot(superstore['Quantity'])

plt.figure(figsize= (12, 6))

sns.kdeplot(superstore['Discount'])

"""We can see that:-
1) Most of the sales values are low.

2) Most of the customers order of around 2-6 quantity of any  category.

3) Not much discounts are given on the categories.

BIVARIATE ANALYSIS OF THE DATA
"""

plt.figure(figsize= (12, 6))

correlations= superstore.corr()
sns.heatmap(correlations, annot= True)

"""We don't have any relation between the numerical features."""

plt.figure(figsize= (16, 8))
sns.barplot(x= 'Sub-Category', y= 'Sales', data= superstore)

"""Things in the sub-category which had the maximum sales are:
1) Copiers
2) Machines

Things in sub-category which had the lowest sales are:
1) Fasteners
2) Art
3) Labels
"""

plt.figure(figsize= (16, 8))
sns.boxplot(x= 'Sub-Category', y= 'Profit', data= superstore)

"""We can see that:-
1) Copiers is showing good profit.

2) Machines, which was showing heavy amount of sales, actually don't show much profit and also shows loss in many cases.

3) Binders, which didn't have much sales, is actually showing good profit than Machines. 
"""

plt.figure(figsize= (16, 8))
sns.boxplot(x= 'Sub-Category', y= 'Discount', data= superstore)

"""1) Here we can see some Outliers in the Furnishings and Appliances sub-category.

2) Heavy discounts are given on Binders and Machines.

"""

plt.figure(figsize= (16, 8))
sns.boxplot(x= 'Sub-Category', y= 'Quantity', data= superstore)

"""There are many Outliers in the 'Quantity' column and almost all the Sub-categories have similar data."""

