# -*- coding: utf-8 -*-
"""Student score.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o4AIlNgGkMwyXDdvygGZWMx5BhjTWEVg

### **VIKASH NAG**

## Prediction using Supervised ML

● Predict the percentage of an student based on the no. of study hours. 

● This is a simple linear  regression task as it involves just 2 variables.

● You can use R, Python, SAS Enterprise Miner or any other tool

● Data can be found at http://bit.ly/w-data

● What will be predicted score if a student studies for 9.25 hrs/ day?

● Task submission: 1. Host the code on GitHub Repository (public). Record the code and output in a video. Post the video on YouTube 2. Share links of code (GitHub) and video (YouTube) as a post on YOUR LinkedIn profile, not TSF Network. 3. Submit the LinkedIn link in Task Submission Form when shared.

IMPORTING NECESSARY LIBRARIES
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

"""LOADING THE DATA"""

score= pd.read_csv('/content/drive/My Drive/Datasets/student_scores - student_scores.csv')

"""FIRST FIVE ROWS OF THE DATASET"""

score.head()

"""DIVIDING THE DATA INTO FEATURES AND LABELS"""

features= score['Hours'].values.reshape(-1, 1)           # converting it into 2-D array
labels= score['Scores'].values.reshape(-1, 1)            # converting it into 2-D array

"""SEPARATING THE DATA INTO TRAINING AND TESTING DATA"""

X_train, X_test, y_train, y_test= train_test_split(features,
                                                   labels,
                                                   test_size= 0.2)

X_train

y_train

X_test

y_test

"""DEFINING THE LINEAR REGRESSION MODEL"""

lr= LinearRegression()
lr.fit(X_train, y_train)

"""PREEDICTING THE MODEL ON THE TEST DATA"""

y_pred= lr.predict(X_test)
y_pred

"""PREEDICTING THE PERCENTAGE OF A STUDENT WHEN HE/SHE STUDIES 9.25 HRS/DAY"""

lr.predict([[9.25]])

"""So a student studying for 9.25 hrs/day will probably have around 93%."""